### ISSUE TITLE
Add code samples to readme

### ISSUE THREAD

**Issue by ZevEisenberg** [Gabardone/AutoLayoutHelpers#1]
Yaml code block should also have a language tag so it gets syntax highlighted 😉

**Comment by omv-libs** [comment]
Can you point me to an example to how to set that up? I'm a bit lost around all the little details of publishing a repo (talk about an organic grown set of little things...).

**Comment by ZevEisenberg** [comment]
Like this! (Edit my post to see the raw formatting.)

```yaml
someArray:
  - foo
  - bar
```

Or this:

```swift
print("hello, world!")
```

**Comment by omv-libs** [comment]
🙏🏼

**Comment by omv-libs** [comment]
Ok I think it's good now on `main`. Let me know if any further improvements are warranted.

Next time I'll actually follow process and add a PR and whatnot 😅

I'll do a 1.0.1 release later so that's what people get if they add the package.
